### ISSUE TITLE
[regression] Fails to install into the stage directory: Prefix /usr/local not writable

### ISSUE THREAD

**Issue by svigerske** [coin-or/ADOL-C#17]
Issue created by migration from Trac.

Original creator: yurivict

Original creation time: 2020-02-01 16:42:44

Assignee: @awalther1

Version: 

Error:

```
  Prefix /usr/local not writable
  please run ./configure --prefix=DIR
  with a writable directory path otherwise administrator privileges
  will be required to run `make install'
```

2.6.3 was building fine.
2.7.1 now has this problem.

**Comment by yurivict** [comment]
Not a problem any more in 2.7.2

**Comment by awalther1** [comment]
Hi, we had this problem with the releases 2.7.0 and 2.7.1. This should be fixed now.
