### ISSUE TITLE
cleanup wiki pages

### ISSUE THREAD

**Issue by svigerske** [coin-or/ADOL-C#18]
Tickets and wiki from Trac were migrated to this GitHub project and the Trac system was set read-only.

Can you look into cleaning up the wiki pages (https://github.com/coin-or/ADOL-C/wiki), e.g., check formatting errors?
You may also consider to just merge all wiki pages into one README.md, committed to the code git repository.

**Comment by svigerske** [comment]
I added the current content (that is not the commit history) of directories html/doc and misc from the svn repo to branch gh-pages in the qpOASES git repo.
Users can then access the content via URLs like https://coin-or.github.io/qpOASES/doc/3.0/doxygen/index.html or https://coin-or.github.io/qpOASES/misc/binaries/3.0.0/matlab/qpOASES.m

The `https://www.coin-or.org/qpOASES/*` links still work at the moment, but they are fed from the svn repo and I presume these links will cease to work at some point or some general redirect will be setup.

**Comment by svigerske** [comment]
Sorry, wrong project. Will delete this comment.

**Comment by awalther1** [comment]
Hi Stefan,

thanks a lot for your support with respect to the move to github. I checked and updated the wiki pages. They should be OK now.

Best regards

Andrea
