### ISSUE TITLE
 can't open file 'setup.py'

### ISSUE THREAD

**Issue by bradbell** [coin-or/ADOL-C#22]
I am getting the error message above during a 'make install'.
Here are the steps to reproduce the problem

    git clone https://github.com/coin-or/ADOL-C.git adolc.git
    cd adolc.git
    git checkout master
    autoreconf --force --install
    mkdir build
    cd build
    ../configure \
        --prefix=/home/bradbell/prefix/adolc  \
        --with-colpack=/home/bradbell/prefix/colpack  \
        --libdir=/home/bradbell/prefix/adolc/lib64  \
        --enable-static  \
        --enable-shared  \
        --with-cflags='-g -O0'  \
        --with-cxxflags='-g -O0'  \
        --enable-docexa  \
        --enable-addexa
    make install

Here is some information about my system:

    adolc.git>uname -a
    Linux localhost.localdomain 5.3.7-301.fc31.x86_64 #1 SMP Mon Oct 21 19:18:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

    adolc.git>git show-ref master
    34227950ffac4619183932dc26eb735d1eb182cf refs/heads/master

    adolc.git>python --version
    Python 3.7.4

    adolc.git>find . -name setup.py
    ./ADOL-C/swig/setup.py

    adolc.git>swig -version
    SWIG Version 4.0.1
    Compiled with g++ [x86_64-redhat-linux-gnu]
    Configured options: +pcre

    adolc.git>g++ --version
    g++ (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
    
Here is a more complete error message:

    cd build
    build>make install > junk
    /usr/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory
    make[3]: *** [Makefile:492: install] Error 2
    make[2]: *** [Makefile:560: install-recursive] Error 1
    make[1]: *** [Makefile:720: install] Error 2
    make: *** [Makefile:536: install-recursive] Error 1

**Comment by awalther1** [comment]
Hi,

this problem should be fixed with the comment from Kshitij last week.

**Comment by bradbell** [comment]
I confirmed that the setup.py problem was fixed for my system.
