### ISSUE TITLE
Preprocessor should not check if C++11 is available

### ISSUE THREAD

**Issue by schulz0r** [coin-or/ADOL-C#26]
Dear developer,
I try to include ADOL-C in a CMake project on MacOS X and encountered problems with the file adouble.h. There is a check if the c++11 flag has been set which is something the build system should do, not the preprocessor. The compiler can support C++11 without explicitly setting a flag, which is the case here.
I can work around this problem by explicitly adding a c++11 flag to my CMake settings, but it should be possible to compile it anyway.
Please move this check to your configure script so that people who include this project into their CMake build system can easily do so.

Thanks

Schulz0r

**Comment by awalther1** [comment]
Hi, 

thanks for the suggestion. We will incorporate it as soon as possible.

Best regards

Andrea Walther

**Comment by awalther1** [comment]
Hi, 

this should be fixed now.

Best regards

Andrea Walther
