### ISSUE TITLE
Linker error using fixpoint iteration abilities

### ISSUE THREAD

**Issue by bertl1234** [coin-or/ADOL-C#31]
Hello,

i got an issue when using fixpoint iteration abilities. 
I used VS17 to compile library with "nosparse" and tried my own examples (with ipopt) - works well without issues. But when using fixpoint iteration abilities (fp_iteration) there occures a linker error. Same when linking the example (fixpoint_exam.cpp):

1>TestFixPoint.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "fp_iteration" in Funktion "main".
(Sorry, VS uses german language on this machine.)

The compiler finds adolc.h and fixpoint.h and the linker also links to adolc.lib (like my other projects). 

Best regards,
Robert

**Comment by bertl1234** [comment]
Solved: Added "ADOLC_DLL_EXPORT" to fixpoint.h. With this modification the function is in the DLL available and the example links correctly.
Signature now in fixpoint.h: 
"ADOLC_DLL_EXPORT int fp_iteration ( int        sub_tape_num ...."

**Comment by awalther1** [comment]
Great, thanks a lot for pointing this out! I modified already the corresponding file.

Best regards

Andrea
