### ISSUE TITLE
Output tape to c or C++ file

### ISSUE THREAD

**Issue by optstat** [coin-or/ADOL-C#34]
I want to output the results of a recorded tape to a C or C++ file for static compilation instead of relying on operator overloading.  Since it is possible to output to latex I imagine that is possible.  Do you have any pointers for how to accomplish that?  
Thank you.

**Comment by awalther1** [comment]
Hi, thanks for your question. In principle it should be possible to generate a C or a C++ file out of the tape information. However, we never implemented something like this. Sorry for this bad news.
Best regards Andrea
