### ISSUE TITLE
Warning in calling setNumDir

### ISSUE THREAD

**Issue by vryy** [coin-or/ADOL-C#52]
When calling `setNumDir` in a C++ code, I always get this warning

    ADOL-C Warning: Tapeless: Setting numDir could change memory allocation of
    derivatives in existing adoubles and may lead to erronious results
    or memory corruption

The code however runs fine. Is there any potential issue with the warning above? Using a small test case, the warning does not occur. Therefore, I don't know where this can come from. Do you have idea to avoid this warning?

**Comment by awalther1** [comment]
Hi,

rethinking the whole issue, the warning is now deleted for the standard use.

Best

Andrea
