### ISSUE TITLE
安装，在make的时候出现如下错误

### ISSUE THREAD

**Issue by james1kobby** [coin-or/ADOL-C#54]
Making all in ADOL-C
make[1]: Entering directory '/home/ubuntu/SOURCE/adolc-version/adolc_source/ADOL-C-master/ADOL-C'
Makefile:525: .deps/dummy.Plo: 没有那个文件或目录
make[1]: *** No rule to make target '.deps/dummy.Plo'。 停止。
make[1]: Leaving directory '/home/ubuntu/SOURCE/adolc-version/adolc_source/ADOL-C-master/ADOL-C'
Makefile:537: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by alecjacobson** [comment]
Another user with the same problem

**Comment by alecjacobson** [comment]
There seems to be something broken on the master branch. If i checkout the releases/2.7.2 commit 0e8f8a62715b7f71f05cbb3b371157aef5d24f94 then make succeeds (on linux).

**Comment by awalther1** [comment]
Hi, I just complied the master branch, for me everything worked fine 
did you execute

autoreconf -fi 

before the compilation?

**Comment by alecjacobson** [comment]
yes, I can reproduce that error with:

```
git clone git@github.com:coin-or/ADOL-C.git ADOL-C-main
cd ADOL-C-main
autoreconf -fi
./configure 
make
```

If it's helpful here's what `uname -a && lsb_release -a && gcc --version && automake --version`

```
Linux elf7910 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

automake (GNU automake) 1.15.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

**Comment by TimSiebert1** [comment]
Hi,

are there still issues @alecjacobson @walk-in-the-dark @james1kobby?
