### ISSUE TITLE
make fail cause not include <algorithm>

### ISSUE THREAD

**Issue by Ybt-1** [coin-or/ADOL-C#59]
`bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -I../../ADOL-C/include -I../../ADOL-C/include -I../../ADOL-C/src  -O2  -DADOLC_INTERNAL=1 -g -O2 -MT tape_handling.lo -MD -MP\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../ADOL-C/include -I../../ADOL-C/include -I../../ADOL-C/src -O2 -DADOLC_INTERNAL=1 -g -O2 -MT tape_handling.lo -MD -MP -MF .deps/tape_handling.Tpo -c tapeo
tape_handling.cpp: In function ‘int initNewTape(short int)’:
tape_handling.cpp:200:49: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  200 |     vector<TapeInfos *>::iterator tiIter = std::find_if(ADOLC_TAPE_INFOS_BUFFER.begin(),
      |                                                 ^~~~~~~
      |                                                 find
tape_handling.cpp: In function ‘void openTape(short int, char)’:
tape_handling.cpp:314:49: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  314 |     vector<TapeInfos *>::iterator tiIter = std::find_if(ADOLC_TAPE_INFOS_BUFFER.begin(),
      |                                                 ^~~~~~~
      |                                                 find
tape_handling.cpp: In function ‘TapeInfos* getTapeInfos(short int)’:
tape_handling.cpp:409:24: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  409 |     auto tiIter = std::find_if(ADOLC_TAPE_INFOS_BUFFER.begin(),
      |                        ^~~~~~~
      |                        find
tape_handling.cpp: In function ‘void setTapeInfoJacSparse(short int, SparseJacInfos)’:
tape_handling.cpp:472:49: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  472 |     vector<TapeInfos *>::iterator tiIter = std::find_if(ADOLC_TAPE_INFOS_BUFFER.begin(),
      |                                                 ^~~~~~~
      |                                                 find
tape_handling.cpp: In function ‘void setTapeInfoHessSparse(short int, SparseHessInfos)’:
tape_handling.cpp:510:49: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  510 |     vector<TapeInfos *>::iterator tiIter = std::find_if(ADOLC_TAPE_INFOS_BUFFER.begin(),
      |                                                 ^~~~~~~
      |                                                 find
tape_handling.cpp: In function ‘int removeTape(short int, short int)’:
tape_handling.cpp:748:49: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  748 |     vector<TapeInfos *>::iterator tiIter = std::find_if(ADOLC_TAPE_INFOS_BUFFER.begin(),
      |                                                 ^~~~~~~
      |                                                 find
make[4]: *** [Makefile:707：tape_handling.lo] 错误 1
make[4]: 离开�录“/mnt/data/ADOL-C/ADOL-C/src”
make[3]: *** [Makefile:727：all-recursive] 错误 1
make[3]: 离开�录“/mnt/data/ADOL-C/ADOL-C/src”
make[2]: *** [Makefile:530：all] 错误 2
make[2]: 离开�录“/mnt/data/ADOL-C/ADOL-C/src”
make[1]: *** [Makefile:571：all-recursive] 错误 1
make[1]: 离开�录“/mnt/data/ADOL-C/ADOL-C”
make: *** [Makefile:536：all-recursive] 错误 1
root@tegra-ubuntu:/mnt/data/ADOL-C#`
As mentioned above: `#include<algorithm>`  needs to be added in ADOL-C/ADOL-C/src/tape_handling.cpp

**Comment by TimSiebert1** [comment]
Hi @Ybt-1 ,

could you please try to compile adolc with cmake, or otherwise provide us the commands you used to compile it?
